version: '2'

services:

  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=42EXP

  node:
    container_name: node
    build: .
    links:
      - postgres:postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: npm start

volumes:
  postgresdata:
