version : '2'

services:
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    links:
      - node:node
    volumes_from:
      - node
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl

  node:
    container_name: node
    build: .
    env_file: .env
    volumes:
      - /usr/src/app
      - ./logs:/usr/src/app/logs
    expose:
      - "8000"
    environment:
      - NODE_ENV=production

    command: npm run package
