version: '2'

services:
  node:
    container_name: node
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    environment:
      - NODE_ENV=development

  test-postgres:
    container_name: test-postgres
    build: ./postgres-test
    volumes:
      - test_postgres_data:/var/lib/postgresql/data


volumes:
  test_postgres_data:
