version: '2'

services:
  web:
    container_name: web
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm start
    environment:
      - NODE_ENV=development
    ports:
      - "8000:8000"
      - "8080:8080"

  postgres:
    ports:
      - "5432:5432"

volumes:
  node_modules:
