version: '2'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - /42EXP/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=42EXP

  node:
    build: .
    links:
      - postgres:postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: npm start
